obj-$(CONFIG_ARM64_MPAM_DRIVER)			+= mpam.o
mpam-y						+= mpam_devices.o
mpam-$(CONFIG_ARM64_MPAM_RESCTRL_FS)		+= mpam_resctrl.o

ccflags-$(CONFIG_ARM64_MPAM_DRIVER_DEBUG)	+= -DDEBUG

obj-$(CONFIG_RISCV_CBQRI_DRIVER)		+= cbqri.o
cbqri-y						+= cbqri_devices.o

ccflags-$(CONFIG_RISCV_CBQRI_DRIVER_DEBUG)	+= -DDEBUG
